### ISSUE TITLE
Trying to run on new program

### ISSUE THREAD

**Issue by Palashio** [Dongdongshe/neuzz#10]
I'm trying to run my new program on neuzz.

Ubuntu 18.0.4. My folders look like this inside of the terminal with neuzz_in having all the training examples as a result of running afl-fuzz on example.exe (compiled program).

![image](https://user-images.githubusercontent.com/35114859/55444642-6da43480-5585-11e9-9c82-fd3ff5fb764b.png)

When I run 
python ./example.exe -a

and 

./neuzz -i neuzz_in -o seeds -l 7506 ./example.exe -a @@ 

I get this error: 

![image](https://user-images.githubusercontent.com/35114859/55444703-a3e1b400-5585-11e9-86ec-66f04f4cebd5.png)

In the other terminal: I get this error: 

![image](https://user-images.githubusercontent.com/35114859/55444743-d8557000-5585-11e9-9b71-e79d0fa0aa8a.png)

**Comment by Dongdongshe** [comment]
1. Use python2.7 instead of python3.
2. Delete all the files inside crashes folder before you run NEUZZ.

**Comment by Palashio** [comment]
I still get this error: 

![image](https://user-images.githubusercontent.com/35114859/55600164-ded01d00-5728-11e9-8e8d-105d664494cf.png)

**Comment by Dongdongshe** [comment]
Please see #9.

**Comment by Palashio** [comment]
Thank you! It turns out my input corpus aren't properly processed into an np array. How would I fix this? Just process the values into an np.array as a part of the base file? Not really sure.

**Comment by Dongdongshe** [comment]
I would suggest you use a python debugger like ipdb to insert a break point at the crashing point and investigate this issue. The nn.py is actually a very simple python code with some comments. It is not that hard to debug function process_data(). A simple example to use ipdb is as follows: 
import ipdb
ipdb.set_trace() #put at locations where you want to insert a break point.
