### ISSUE TITLE
Some questions about the part of Mutation and Retraining in the paper

### ISSUE THREAD

**Issue by HU-HW** [Dongdongshe/neuzz#11]
Your paper is well written, and the idea is innovative.
I have some question about the part of Mutation and Retraining in the section V IMPLEMENTATION.
1. How did you get the 5,120 mutated inputs for a seed input? I could't understand that why it is the number 5120.
2. What does it mean that "Next, we randomly choose 100 output neurons representing 100 unexplored edges in the target program and generate 10,240 mutated inputs from two seeds"?
3. In the Algorithm 1, is the gen_mutate  executed twice for each m? or you just check the sign of the gradient for each of these bytes to decide the direction of the mutation, is it only executed once? 
thank you .

**Comment by Dongdongshe** [comment]
Hi, thank you for interest.
1. For each seed, we perform 10 sets of mutation schemes. Each schemes is executed twice (i.e, following the sign of gradients, then following the reverse sign of gradient). So total is 10*2*256. You can check the mutation code in neuzz.c for details.
2. We choose 100 edges which is not explored during last round. Then for each edge, we choose 2 seeds, each seed would generate 5120 mutations as mentioned before. So total number is 100 * 2 * 5120 = 1M.
3. You are right. For every m, gen_mutate is only executed twice.

**Comment by JialeDeng** [comment]
Hi, Dongdong!
I am also reading your paper, I know that you use the NN to do the program smoothing, but I didn't find the obvious method of NN smoothing in neuzz.c and nn.py. May I ask how you realize NN smoothing? (or maybe I missed some details in the source code...
