### ISSUE TITLE
training data

### ISSUE THREAD

**Issue by sp4rky444** [Dongdongshe/neuzz#5]
i'm running neuzz in a linux enviroment.

How do I generate more training data on the programs (readelf, etc.) and then view it?

**Comment by f1reburner** [comment]
From my understanding, the outputs are the bitmaps.

**Comment by Dongdongshe** [comment]
More training data will be automatically generated during fuzzing process. Neuzz will select add inputs which cover new edge coverage into training data after every fuzzing round. As @f1reburner said, the training datasets are in (inputs, edge coverage) pair. The inputs are located in seeds directory and the edge coverage are located in bitmaps directory. You can view them by checking files in these two directories.

**Comment by Palashio** [comment]
Oh this is interesting! I've actually got a question about this - How would I view those inputs, as something interpretable to an individual? The file type I get for the seeds is an ELF 32-bit LSB Intel 80386 Version.

**Comment by Palashio** [comment]
Additionally, i'm confused as how to how the edge coverage bitmaps represent how much the neuzz "covers". How would I interpret that?
