### ISSUE TITLE
Unable to open files

### ISSUE THREAD

**Issue by Palashio** [Dongdongshe/neuzz#6]
After switching to a GPU based Azure Machine i've run into another problem I can't fix. 

1) Ubuntu 18.0.4
2) Built neuzz using  gcc -O3 -funroll-loops ./neuzz.c -o neuzz
3) Followed steps given by the README ~all steps ran except for this line: echo performance | tee cpu*/cpufreq/scaling_governor

This is what my readelf folder looks like now

![image](https://user-images.githubusercontent.com/35114859/54171792-0b5a8700-4452-11e9-9f3a-58371639c377.png)

Whenever I run the two modules seperately, this error is returned:

![image](https://user-images.githubusercontent.com/35114859/54171826-1f05ed80-4452-11e9-9098-7fd97c8febea.png)

This is the output in the other terminal:

![image](https://user-images.githubusercontent.com/35114859/54171845-304efa00-4452-11e9-9714-6345ddf1b596.png)

**Comment by Dongdongshe** [comment]
It seems a python-3.5 grammar error. Please try to run the code with python-2.7.

**Comment by Palashio** [comment]
How can I accomplish this? I attempted to run using python2.7 nn.py ./readelf -a, and tried to revert to older python using conda install python=2.7

**Comment by Palashio** [comment]
Solved. Created conda enviroment using specifications.
