### ISSUE TITLE
Viewing files in an interpretable manner

### ISSUE THREAD

**Issue by Palashio** [Dongdongshe/neuzz#7]
Asked this question in a closed question, but would rather just start a new discussion.

So I've succesfully ran NEUZZ, thanks to your help! Now, i've got the crash information, the bitmaps, and the seeds. 

How do I view each of them in an interpretable manner? The crash information is in a one dimensional array, while the bitmaps and seeds are in an ELF file.

**Comment by Dongdongshe** [comment]
The crash inputs generated by neuzz are automatically saved into crash folder. You can reproduce the crash and perform further analysis (such as gdb, taint analysis) with the saved input. What do you mean by viewing them in an interpretable manner?

**Comment by Palashio** [comment]
How would I reproduce the crash? Aren't the crashes in an array format, so i can't feed them to the readelf program right?

Also for the interpretable manner specifically, I meant how would I view the seeds that represent the inputs in a way that any programmer would understand. They're currently ELF files in the seeds directory.

**Comment by Dongdongshe** [comment]
The readelf binary would take a ELF as input. To reproduce the crash, simply run ./readelf -a crash/file_name.

**Comment by Dongdongshe** [comment]
Btw, please do not post any questions not related to the bug of code in the issue. If you have any question, please reach me through email.

**Comment by Palashio** [comment]
Couldn't find it anywhere. I'd really like to converse further over email though.
