### ISSUE TITLE
Not able to run new program

### ISSUE THREAD

**Issue by Palashio** [Dongdongshe/neuzz#8]
I'm trying to run neuzz on a new program and am currently setting it up.

I've compiled it using the gcc command given and currently have a folder named example with example.c and its compiled version example in it. I can't seem to run afl on the example for this step: 

Collect the training data by running AFL on the binary for a while(about an hour), then copy the queue folder to neuzz_in.

**Comment by Dongdongshe** [comment]
Could you provide more detail of why you cannot run AFL on the binary? To run AFL on your example binary, you first need to compile it with afl-gcc, then run afl-fuzz on the afl-instrumented binary. Please check AFL document for details.

**Comment by Palashio** [comment]
well i compiled the program into an executable using this: 

gcc -w ./example.c -o example -lm

Now, I can't seem to run afl-gcc on it to produce the test cases. How would I do that?

**Comment by Dongdongshe** [comment]
Please read AFL document for more detail about running afl-gcc. Again, do not open a issue that is not related to NEUZZ bug. If you have any question about running this tool, please contact me through email.

**Comment by Palashio** [comment]
I can't find your email anywhere - what is it?
